{{- if or .Values.gandiApiToken .Values.gandiPat }}
apiVersion: v1
kind: Secret
metadata:
  name: gandi-credentials
  namespace: {{ .Values.certManager.namespace | quote }}
  labels:
    {{- include "cert-manager-webhook-gandi.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.gandiApiToken }}
  api-token: {{ .Values.gandiApiToken | toString | b64enc | quote }}
{{- end }}
{{- if .Values.gandiPat }}
  pat: {{ .Values.gandiPat | toString | b64enc | quote }}
{{- end }}
{{- end }}